M48
; DRILL file {KiCad 6.0.0-d3dd2cf0fa~116~ubuntu20.04.1} date Sun 02 Jan 2022 10:53:39 AM EST
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-01-02T10:53:39-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.0-d3dd2cf0fa~116~ubuntu20.04.1
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X120.7Y-26.38
X120.7Y-148.88
T0
M30
